ALTER TABLE MINECRAFT.GAMES ADD COLUMN modified TIMESTAMP(3);
UPDATE MINECRAFT.GAMES SET modified=start_time WHERE modified=null ;

ALTER TABLE MINECRAFT.GAMES DROP COLUMN start_time;

ALTER TABLE MINECRAFT.GAMES
ADD COLUMN start_time TIMESTAMP(3) ;

UPDATE MINECRAFT.GAMES SET start_time=modified WHERE start_time=null ;

ALTER TABLE MINECRAFT.GAME_LOGS MODIFY COLUMN timestamp TIMESTAMP(3);
