name: publish

on:
  push:
    tags:
     - 'release-*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.17
      uses: actions/setup-java@v1
      with:
        java-version: 1.17
    - name: Build with Gradle
      env:
        GPR_USER: x-access-token
        GPR_API_KEY: ${{ secrets.BOT_TOKEN }}
      run: ./gradlew publish
